/* eslint-disable */
import * as types from './graphql';

type Documents = {
    "\n  query GetMenu($handle: String!) {\n      menu(handle: $handle) {\n        items {\n          title\n          url\n          items {\n            title\n            url\n          }\n        }\n      }\n    }\n      \n\n": typeof types.GetMenuDocument,
    "\n  query GetMenu($handle: String!) {\n    menu(handle: $handle) {\n      items {\n        title\n        url\n        items {\n          title\n          url\n        }\n      }\n    }\n  }\n": typeof types.GetMenuDocument,
    "\n  query ProductByHandle($handle: String!) {\n    product(handle: $handle) {\n      id\n      title\n      handle\n      descriptionHtml\n      priceRange {\n        minVariantPrice {\n          amount\n          currencyCode\n        }\n      }\n      options {\n        name\n        values\n      }\n      media(first: 20) {\n        edges {\n          node {\n            ... on MediaImage {\n              id\n              image {\n                url\n                altText\n                width\n                height\n              }\n            }\n          }\n        }\n      }\n      variants(first: 20) {\n        edges {\n          node {\n            id\n            title\n            availableForSale\n            selectedOptions {\n              name\n              value\n            }\n            price {\n              amount\n              currencyCode\n            }\n            image {\n              url\n              altText\n              width\n              height\n            }\n            variantProfile: metafield(\n              namespace: \"bridgeFor\"\n              key: \"Varianthandler\"\n            ) {\n              reference {\n                ... on Metaobject {\n                  images: field(key: \"images\") {\n                    value\n                  }\n                  subtitle: field(key: \"subtitle\") {\n                    value\n                  }\n                  materials: field(key: \"materials\") {\n                    value\n                  }\n                  functions: field(key: \"functions\") {\n                    value\n                  }\n                  properties: field(key: \"properties\") {\n                    value\n                  }\n                  usage: field(key: \"usage\") {\n                    value\n                  }\n                  sizeFit: field(key: \"size_fit\") {\n                    value\n                  }\n                  storageAndMaintenance: field(key: \"storage_and_maintenance\") {\n                    value\n                  }\n                  colorLabel: field(key: \"color_label\") {\n                    value\n                  }\n                  backgroundColor: field(key: \"background_color\") {\n                    value\n                  }\n                  swatchHexcolorForVariant: field(\n                    key: \"swatch_hexcolor_for_variant\"\n                  ) {\n                    value\n                  }\n                  length: field(key: \"length\") {\n                    value\n                  }\n                  centerToWrist: field(key: \"center_to_wrist\") {\n                    value\n                  }\n                  flatWidth: field(key: \"flat_width\") {\n                    value\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.ProductByHandleDocument,
    "\n  query GetProductByHandle($first: Int!, $query: String!) {\n    products(first: $first, query: $query) {\n      edges {\n        node {\n          id\n          title\n          handle\n          featuredImage {\n            url\n            altText\n          }\n          priceRange {\n            minVariantPrice {\n              amount\n              currencyCode\n            }\n          }\n          compareAtPriceRange {\n            maxVariantPrice {\n              amount\n              currencyCode\n            }\n          }\n          variants(first: 1) {\n            edges {\n              node {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetProductByHandleDocument,
    "\n  query GetProductByHandleQuery($first: Int!, $query: String!) {\n    products(first: $first, query: $query) {\n      edges {\n        node {\n          id\n          title\n          handle\n          featuredImage {\n            url\n            altText\n          }\n          priceRange {\n            minVariantPrice {\n              amount\n              currencyCode\n            }\n          }\n          compareAtPriceRange {\n            maxVariantPrice {\n              amount\n              currencyCode\n            }\n          }\n          variants(first: 1) {\n            edges {\n              node {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetProductByHandleQueryDocument,
    "\n  query ShopifyProducts($first: Int!) {\n    products(first: $first) {\n      edges {\n        node {\n          id\n          title\n        }\n      }\n    }\n  }\n": typeof types.ShopifyProductsDocument,
};
const documents: Documents = {
    "\n  query GetMenu($handle: String!) {\n      menu(handle: $handle) {\n        items {\n          title\n          url\n          items {\n            title\n            url\n          }\n        }\n      }\n    }\n      \n\n": types.GetMenuDocument,
    "\n  query GetMenu($handle: String!) {\n    menu(handle: $handle) {\n      items {\n        title\n        url\n        items {\n          title\n          url\n        }\n      }\n    }\n  }\n": types.GetMenuDocument,
    "\n  query ProductByHandle($handle: String!) {\n    product(handle: $handle) {\n      id\n      title\n      handle\n      descriptionHtml\n      priceRange {\n        minVariantPrice {\n          amount\n          currencyCode\n        }\n      }\n      options {\n        name\n        values\n      }\n      media(first: 20) {\n        edges {\n          node {\n            ... on MediaImage {\n              id\n              image {\n                url\n                altText\n                width\n                height\n              }\n            }\n          }\n        }\n      }\n      variants(first: 20) {\n        edges {\n          node {\n            id\n            title\n            availableForSale\n            selectedOptions {\n              name\n              value\n            }\n            price {\n              amount\n              currencyCode\n            }\n            image {\n              url\n              altText\n              width\n              height\n            }\n            variantProfile: metafield(\n              namespace: \"bridgeFor\"\n              key: \"Varianthandler\"\n            ) {\n              reference {\n                ... on Metaobject {\n                  images: field(key: \"images\") {\n                    value\n                  }\n                  subtitle: field(key: \"subtitle\") {\n                    value\n                  }\n                  materials: field(key: \"materials\") {\n                    value\n                  }\n                  functions: field(key: \"functions\") {\n                    value\n                  }\n                  properties: field(key: \"properties\") {\n                    value\n                  }\n                  usage: field(key: \"usage\") {\n                    value\n                  }\n                  sizeFit: field(key: \"size_fit\") {\n                    value\n                  }\n                  storageAndMaintenance: field(key: \"storage_and_maintenance\") {\n                    value\n                  }\n                  colorLabel: field(key: \"color_label\") {\n                    value\n                  }\n                  backgroundColor: field(key: \"background_color\") {\n                    value\n                  }\n                  swatchHexcolorForVariant: field(\n                    key: \"swatch_hexcolor_for_variant\"\n                  ) {\n                    value\n                  }\n                  length: field(key: \"length\") {\n                    value\n                  }\n                  centerToWrist: field(key: \"center_to_wrist\") {\n                    value\n                  }\n                  flatWidth: field(key: \"flat_width\") {\n                    value\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.ProductByHandleDocument,
    "\n  query GetProductByHandle($first: Int!, $query: String!) {\n    products(first: $first, query: $query) {\n      edges {\n        node {\n          id\n          title\n          handle\n          featuredImage {\n            url\n            altText\n          }\n          priceRange {\n            minVariantPrice {\n              amount\n              currencyCode\n            }\n          }\n          compareAtPriceRange {\n            maxVariantPrice {\n              amount\n              currencyCode\n            }\n          }\n          variants(first: 1) {\n            edges {\n              node {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetProductByHandleDocument,
    "\n  query GetProductByHandleQuery($first: Int!, $query: String!) {\n    products(first: $first, query: $query) {\n      edges {\n        node {\n          id\n          title\n          handle\n          featuredImage {\n            url\n            altText\n          }\n          priceRange {\n            minVariantPrice {\n              amount\n              currencyCode\n            }\n          }\n          compareAtPriceRange {\n            maxVariantPrice {\n              amount\n              currencyCode\n            }\n          }\n          variants(first: 1) {\n            edges {\n              node {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetProductByHandleQueryDocument,
    "\n  query ShopifyProducts($first: Int!) {\n    products(first: $first) {\n      edges {\n        node {\n          id\n          title\n        }\n      }\n    }\n  }\n": types.ShopifyProductsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetMenu($handle: String!) {\n      menu(handle: $handle) {\n        items {\n          title\n          url\n          items {\n            title\n            url\n          }\n        }\n      }\n    }\n      \n\n"): typeof import('./graphql').GetMenuDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetMenu($handle: String!) {\n    menu(handle: $handle) {\n      items {\n        title\n        url\n        items {\n          title\n          url\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetMenuDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductByHandle($handle: String!) {\n    product(handle: $handle) {\n      id\n      title\n      handle\n      descriptionHtml\n      priceRange {\n        minVariantPrice {\n          amount\n          currencyCode\n        }\n      }\n      options {\n        name\n        values\n      }\n      media(first: 20) {\n        edges {\n          node {\n            ... on MediaImage {\n              id\n              image {\n                url\n                altText\n                width\n                height\n              }\n            }\n          }\n        }\n      }\n      variants(first: 20) {\n        edges {\n          node {\n            id\n            title\n            availableForSale\n            selectedOptions {\n              name\n              value\n            }\n            price {\n              amount\n              currencyCode\n            }\n            image {\n              url\n              altText\n              width\n              height\n            }\n            variantProfile: metafield(\n              namespace: \"bridgeFor\"\n              key: \"Varianthandler\"\n            ) {\n              reference {\n                ... on Metaobject {\n                  images: field(key: \"images\") {\n                    value\n                  }\n                  subtitle: field(key: \"subtitle\") {\n                    value\n                  }\n                  materials: field(key: \"materials\") {\n                    value\n                  }\n                  functions: field(key: \"functions\") {\n                    value\n                  }\n                  properties: field(key: \"properties\") {\n                    value\n                  }\n                  usage: field(key: \"usage\") {\n                    value\n                  }\n                  sizeFit: field(key: \"size_fit\") {\n                    value\n                  }\n                  storageAndMaintenance: field(key: \"storage_and_maintenance\") {\n                    value\n                  }\n                  colorLabel: field(key: \"color_label\") {\n                    value\n                  }\n                  backgroundColor: field(key: \"background_color\") {\n                    value\n                  }\n                  swatchHexcolorForVariant: field(\n                    key: \"swatch_hexcolor_for_variant\"\n                  ) {\n                    value\n                  }\n                  length: field(key: \"length\") {\n                    value\n                  }\n                  centerToWrist: field(key: \"center_to_wrist\") {\n                    value\n                  }\n                  flatWidth: field(key: \"flat_width\") {\n                    value\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').ProductByHandleDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProductByHandle($first: Int!, $query: String!) {\n    products(first: $first, query: $query) {\n      edges {\n        node {\n          id\n          title\n          handle\n          featuredImage {\n            url\n            altText\n          }\n          priceRange {\n            minVariantPrice {\n              amount\n              currencyCode\n            }\n          }\n          compareAtPriceRange {\n            maxVariantPrice {\n              amount\n              currencyCode\n            }\n          }\n          variants(first: 1) {\n            edges {\n              node {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetProductByHandleDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProductByHandleQuery($first: Int!, $query: String!) {\n    products(first: $first, query: $query) {\n      edges {\n        node {\n          id\n          title\n          handle\n          featuredImage {\n            url\n            altText\n          }\n          priceRange {\n            minVariantPrice {\n              amount\n              currencyCode\n            }\n          }\n          compareAtPriceRange {\n            maxVariantPrice {\n              amount\n              currencyCode\n            }\n          }\n          variants(first: 1) {\n            edges {\n              node {\n                id\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').GetProductByHandleQueryDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ShopifyProducts($first: Int!) {\n    products(first: $first) {\n      edges {\n        node {\n          id\n          title\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').ShopifyProductsDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
