// Path: src/app/layout.tsx
import { SpeedInsights } from '@vercel/speed-insights/next'
import { Analytics } from '@vercel/analytics/next'
import type { Metadata } from 'next'
import '@/db/zod/zodConfig'
import { Geist, Geist_Mono } from 'next/font/google'

import { getMenu } from '@/lib/helpers/menu'
import { getCartIdFromCookie } from '@/lib/helpers/cart/getCartIdFromCookie'
import { getCachedCart } from '@/lib/helpers/cart/getCachedCart'
import Providers from '@/components/providers/Providers'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const [mainMenu, cartId] = await Promise.all([getMenu('header-mega-menu'), getCartIdFromCookie()])
  const initialCart = await getCachedCart(cartId)

  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers initialCart={initialCart} cartId={cartId}>
          <Header menu={mainMenu} />
          <main>{children}</main>
          <Footer />
          <SpeedInsights />
          <Analytics mode='development' />
        </Providers>
      </body>
    </html>
  )
}
