export { normalizeProduct } from './normalizeProduct'
export { normalizeProductImage } from './normalizeProductImage'
export { normalizeMenu } from './normalizeMenu'
export { normalizeCart } from './normalizeCart'
export { normalizeShopifyUrl } from './normalizeShopifyUrl'
